# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-04 13:25
from __future__ import unicode_literals

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from pygments import highlight
from pygments.formatters.html import HtmlFormatter
from pygments.lexers import get_lexer_by_name


def highlight_snippets(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Snippet = apps.get_model('snippets', 'Snippet')
    for snippet in Snippet.objects.all():
        lexer = get_lexer_by_name(snippet.language)
        options = {'title': snippet.title} if snippet.title else {}
        formatter = HtmlFormatter(style=snippet.style, linenos=snippet.linenos,
                                  full=True, **options)
        snippet.highlighted = highlight(snippet.code, lexer, formatter)
        snippet.save()


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='highlighted',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='snippet',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(highlight_snippets)
    ]
